# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
  # Pods for RxProject

  target 'RxProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
